### ISSUE TITLE
Diff fails

### ISSUE THREAD

**Issue by hexedsilicon** [theneosloth/Bolas#27]
This command fails
`!diff https://tappedout.net/mtg-decks/rad-farm/ https://tappedout.net/mtg-decks/razaketh-adnaus-scepter\`

My guess is a split card somewhere?

**Comment by theneosloth** [comment]
I got some more reports about this and it seems that diff fails for every website now. Seems like the tappedout format changed so the parser fails, but for some reason using the command with deckstats raises the following
``` 
discord.errors.HTTPException: BAD REQUEST (status code: 400): Invalid Form Body
In embed.fields.0.value: Must be 1024 or fewer in length.
```

Looking into it now

**Comment by jeacaveo** [comment]
I pushed a change that solves the problem for tappedout: #28 

deckstat is working for me.

**Comment by theneosloth** [comment]
That's interesting, it still fails on my end even with the patch. I'll have to see if it has something to do with my network

**Comment by jeacaveo** [comment]
I did some more testng, and the issue seems to be related to sideboards. I'm looking into it, but any insight would be appreciated.

**Comment by jeacaveo** [comment]
Figured it out. Since tappedout doesn't have the .dec format anymore, sideboard cards don't have the following format (they have the same format as the mainboard cards):

`SB:  1 Island`

Also, the title `Sideboard` doesn't start with `//`.

I don't see any of the formats for tappedout that does this and the current regex and logic doesn't account for them.

deckstats is still working fine if both URLs are from that site.

I'll push my proposed fix by the end of the day.

**Comment by theneosloth** [comment]
Merged #28, so the issue should now be fixed for tappedout. Will look into deckstats when I get a chance

**Comment by jeacaveo** [comment]
I havent encountered any issues with deckstats, can you give me more details? maybe I can help.

**Comment by theneosloth** [comment]
It silently fails when I try to compare two deckstats lists, an example I was given in a bug report was: `!diff https://deckstats.net/decks/112347/1364863-budget-zedruu-the-greathearted/en https://deckstats.net/decks/137468/1364301-muldrotha-the-gravetide/en`

Looking at the debug output gives me the exception I mentioned above but I haven't found the time to look into it further than that.

Curiously it seems to work when one of the links is a mtggoldfish link and the other is a deckstats link (I tried `https://deckstats.net/decks/103962/1372125-izzet-wizards/en https://www.mtggoldfish.com/deck/2145072#paper`), but again I haven't done enough thorough testing or looked through the debug output to know what's actually causing the issue

**Comment by jeacaveo** [comment]
Seems to be related to this line:

`1 Zedruu the Greathearted # !Commander`

The only list with that line is the one that keeps failing. The current regex should cover it, but it isn't anymore? I'll look into it in a few hours if you don't get to it first.

**Comment by jeacaveo** [comment]
I was wrong. It had nothing to do with regex or any particular line.

The problem is that the value for the Embed object is too big. The Discord API limits that attribute to 1024 characters, so when the lists have very little in common, the diff is huge.

If you take the same lists in the failing scenario and compare it with other lists from the same commander, it works.

This has always been like this, I think this is a separate issue.

**Comment by theneosloth** [comment]
That makes a lot of sense  and I am surprised I didn't run into that earlier. I think what I'll do that if the diff is too big, then the result should omit the sideboards and if that's still too big then the user will be given an error message

**Comment by theneosloth** [comment]
Fixed the bot not giving an error message when the message is too long in 23c3cc08eb5b3af8b8d5ac20b1977736adbc01bf .
